% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  12pt,
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{setspace}
\makeatletter
\renewcommand\paragraph{\@startsection{paragraph}{4}{\z@}%
        {-2.5ex\@plus -1ex \@minus -.25ex}%
        {1.25ex \@plus .25ex}%
        {\normalfont\normalsize\bfseries}}
\makeatother
\setcounter{secnumdepth}{4}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\author{}
\date{\vspace{-2.5em}}

\begin{document}

\onehalfspacing

\pagenumbering{gobble}

%\begin{titlepage}
\vspace*{\fill}
\begin{center}
\LARGE{\textbf{Analyse descriptive du jeu de données Spotify}}\\
\Large{\textbf{Projet en Statistique descriptive}}\\
\vspace*{1\baselineskip}
\Large{\textbf{Membres}}\\
LOULIDI Younes\\
PHAM Tuan Kiet\\
VO Van Nghia\\
\vfill % equivalent to \vspace{\fill}
\vspace*{\fill}
\Large{\textbf{Date}}\\
17 Mars, 2021
\end{center}
% \end{titlepage}

\newpage
\doublespacing

\hypersetup{linkcolor = black}
\newpage
\renewcommand{\contentsname}{Table des matières}
\pagenumbering{roman}
\tableofcontents
\addcontentsline{toc}{section}{\contentsname}

\newpage
\pagenumbering{arabic}


\hypertarget{statistiques-descriptives-unidimensionnelle-et-bidimensionnelle}{%
\section{Statistiques descriptives unidimensionnelle et
bidimensionnelle}\label{statistiques-descriptives-unidimensionnelle-et-bidimensionnelle}}

\hypertarget{la-nature-des-jeux-de-donnuxe9es}{%
\subsection{La nature des jeux de
données}\label{la-nature-des-jeux-de-donnuxe9es}}

\hypertarget{des-jeux-de-donnuxe9es}{%
\subsubsection{Des jeux de données}\label{des-jeux-de-donnuxe9es}}

Ces jeux de données se composent de 10000 chansons extraites de la base
de données Spotify. Chaque ligne contient 11 variables statistiques
comme suit:

\begin{itemize}
\tightlist
\item
  \texttt{year}: année de sortie du morceau,
\item
  \texttt{acousticness}: métrique relative interne de l'acoustique
  morceau,
\item
  \texttt{duration}: durée du morceau en millisecondes (ms),
\item
  \texttt{energy}: métrique relative interne de l'intensité, des rythmes
  du morceau,
\item
  \texttt{explicit}: vaut 1 si le morceau contient des vulgarités, et 0
  sinon,
\item
  \texttt{key}: tonalité en début de morceau,
\item
  \texttt{liveness}: proportion du morceau où l'on entend un public,
\item
  \texttt{loudness}: mesure relative du volume du morceau (en décibels,
  dB)
\item
  \texttt{mode}: mode du morceau (0 si la tonalité est mineure, et 1 si
  la tonalité est majeure),
\item
  \texttt{tempo}: le tempo du morceau, en battement par minute (bpm),
\item
  \texttt{pop.class}: la popularité du morceau.
\end{itemize}

\hypertarget{des-variables-statistiques}{%
\subsubsection{Des variables
statistiques}\label{des-variables-statistiques}}

Ici, nous précisons la nature de chaque variable et son format dans R.

\begin{longtable}[]{@{}llr@{}}
\toprule
Nom de variable statistique & Type de variable & Format dans R \\
\midrule
\endhead
\texttt{year} & qualitative ordinale & \texttt{integer} \\
\texttt{acousticness} & quantitative continue & \texttt{numeric} \\
\texttt{duration} & quantitative continue\footnote{On choisi son nature
  est de quantitative continue parce que.} & \texttt{numeric} \\
\texttt{energy} & quantitative continue & \texttt{numeric} \\
\texttt{explicit} & qualitative nominale & \texttt{logical} \\
\texttt{key} & qualitative nominale & \texttt{factor} \\
\texttt{liveness} & quantitative continue & \texttt{numeric} \\
\texttt{loudness} & quantitative continue & \texttt{numeric} \\
\texttt{mode} & qualitative nominale\footnote{On pose \texttt{FALSE} si
  la tonalité est mineure et \texttt{TRUE} si non.} &
\texttt{logical} \\
\texttt{tempo} & quantitative continue & \texttt{numeric} \\
\texttt{pop.class} & qualitative ordinale & \texttt{factor} \\
\bottomrule
\end{longtable}

\hypertarget{charger-les-jeux-de-donnuxe9es-dans-r}{%
\subsubsection{Charger les jeux de données dans
R}\label{charger-les-jeux-de-donnuxe9es-dans-r}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LoadDataset }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(fname) \{}
\NormalTok{    colclasses }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
        \StringTok{"integer"}\NormalTok{, }\StringTok{"numeric"}\NormalTok{, }\StringTok{"numeric"}\NormalTok{,}
        \StringTok{"numeric"}\NormalTok{, }\StringTok{"integer"}\NormalTok{, }\StringTok{"factor"}\NormalTok{, }\StringTok{"numeric"}\NormalTok{,}
        \StringTok{"numeric"}\NormalTok{, }\StringTok{"integer"}\NormalTok{, }\StringTok{"numeric"}\NormalTok{, }\StringTok{"factor"}
\NormalTok{    )}
\NormalTok{    dataframe }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(fname, }\AttributeTok{colClasses =}\NormalTok{ colclasses)}
\NormalTok{    dataframe}\SpecialCharTok{$}\NormalTok{explicit }\OtherTok{\textless{}{-}} \FunctionTok{as.logical}\NormalTok{(dataframe}\SpecialCharTok{$}\NormalTok{explicit)}
\NormalTok{    dataframe}\SpecialCharTok{$}\NormalTok{mode }\OtherTok{\textless{}{-}} \FunctionTok{as.logical}\NormalTok{(dataframe}\SpecialCharTok{$}\NormalTok{mode)}
    \FunctionTok{return}\NormalTok{(dataframe)}
\NormalTok{\}}
\NormalTok{daf }\OtherTok{\textless{}{-}} \FunctionTok{LoadDataset}\NormalTok{(}\StringTok{"dataset.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{analyses-unidimensionnelles}{%
\subsection{Analyses
unidimensionnelles}\label{analyses-unidimensionnelles}}

\hypertarget{une-variable-qualitative---pop.class}{%
\subsubsection{\texorpdfstring{Une variable qualitative -
\texttt{pop.class}}{Une variable qualitative - pop.class}}\label{une-variable-qualitative---pop.class}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(daf}\SpecialCharTok{$}\NormalTok{pop.class)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    A    B    C    D 
##  940 2874 3038 3148
\end{verbatim}

Il existe 4 niveaux de popularité (modalités). Commencer par \texttt{A}
est le plus populaire et décroissant avec \texttt{B}, \texttt{C},
\texttt{D}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pop\_class\_table }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(daf}\SpecialCharTok{$}\NormalTok{pop.class)}
\FunctionTok{print}\NormalTok{(}\FunctionTok{label\_percent}\NormalTok{()(}\FunctionTok{c}\NormalTok{(pop\_class\_table) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(pop\_class\_table)), }\AttributeTok{quote =}\NormalTok{ F)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     A     B     C     D 
##  9.4% 28.7% 30.4% 31.5%
\end{verbatim}

\begin{figure}
\centering
\includegraphics{report_files/figure-latex/pop_class_table-1.pdf}
\caption{Diagramme en barre de popularité}
\end{figure}

On peut noter que dans cet ensemble de données, la plupart des chansons
ne sont pas populaires (\(31,5%
\)). Plus le niveau de popularité est élevé, moins les chansons peuvent
atteindre ce niveau.

\hypertarget{une-variable-quantitative---acousticness}{%
\subsubsection{\texorpdfstring{Une variable quantitative -
\texttt{acousticness}}{Une variable quantitative - acousticness}}\label{une-variable-quantitative---acousticness}}

\hypertarget{ruxe9sumuxe9}{%
\paragraph{Résumé}\label{ruxe9sumuxe9}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(daf}\SpecialCharTok{$}\NormalTok{acousticness)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.0961  0.5085  0.4990  0.8930  0.9960
\end{verbatim}

D'après le résultat ci-dessus, on a:

\begin{itemize}
\tightlist
\item
  Le premier quartile \(q_{0.25}\) est \(0.0961\)
\item
  Le deuxième quartile \(q_{0.5}\) est \(0.5085\)
\item
  Le troisième quartile \(q_{0.75}\) est \(0.8930\)
\end{itemize}

\hypertarget{distribution}{%
\paragraph{Distribution}\label{distribution}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{skewness}\NormalTok{(daf}\SpecialCharTok{$}\NormalTok{acousticness)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.01816556
\end{verbatim}

Étant donné que son skewness est approximativement 0, nous pouvons
conclure que l'ensemble de données est centré autour de sa médiane.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kurtosis}\NormalTok{(daf}\SpecialCharTok{$}\NormalTok{acousticness)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -1.613205
\end{verbatim}

Du fait que son kurtosis est inférieur à \(-1,2\) (le kurtosis de la
distribution uniforme\footnote{\url{https://en.wikipedia.org/wiki/Kurtosis\#Other_well-known_distributions}}),
sa distribution aura la forme d'une vallée (car la distribution uniforme
est déjà une ligne).

\begin{figure}
\centering
\includegraphics{report_files/figure-latex/daf_acousticness_boxplot-1.pdf}
\caption{Histogramme d'acoustique des chansons}
\end{figure}

\hypertarget{analyses-bidimensionnelles}{%
\subsection{Analyses
bidimensionnelles}\label{analyses-bidimensionnelles}}

\hypertarget{entre-une-variable-quantitative-et-une-qualitative}{%
\subsubsection{Entre une variable quantitative et une
qualitative}\label{entre-une-variable-quantitative-et-une-qualitative}}

Dans cette partie, nous réutiliserons et analyserons les 2 variables
précédentes (\texttt{pop.class} et \texttt{acousticness}).

\hypertarget{repruxe9sentation-graphique}{%
\paragraph{Représentation graphique}\label{repruxe9sentation-graphique}}

\begin{figure}
\centering
\includegraphics{report_files/figure-latex/daf_acousticness_popclass_boxplot-1.pdf}
\caption{Boxplot parallèles de la relation entre acoustique et
popularité}
\end{figure}

Notez à partir de notre graphique, les cases varient d'un facteur à
l'autre, nous concluons que l'acoustique et la popularité sont liées
l'une à l'autre.

De plus, \(75\%\) des chansons populaires ont une acoustique inférieure
à \(0,5\) tandis que celle de presque \(100\%\) des chansons les moins
populaires est supérieure à \(0,5\). De l'autre côté, selon la partie
précédente, la distribution des chansons avec l'acoustique est
symétrique autour de sa médiane (ce qui indique qu'il y a presque le
même nombre de chansons de 2 types). Il est démontrable que les gens
aiment les chansons électroniques.

\hypertarget{indice-de-liaison}{%
\paragraph{Indice de liaison}\label{indice-de-liaison}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{eta2}\NormalTok{(daf}\SpecialCharTok{$}\NormalTok{acousticness, daf}\SpecialCharTok{$}\NormalTok{pop.class)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.3673706
\end{verbatim}

Avec \(c_{y|x} \approx 0,4\), il existe une légère relation entre deux
variables.

\end{document}
